logPath: "D:/lillusory/projects/i-go"
redis:
  addr: "123.57.236.125:6379"
  password: "123456"
  db: 0
  MaxRetries: 3
  PoolSize: 10
  MinIdleConns: 10
  MaxConnAge: "30s"
  PoolTimeout: "10s"
  IdleTimeout: "10s"
  IdleCheckFrequency: "10s"

mongodb:
  appUrl: "123.57.236.125:27017"
  username: "test"
  password: "123456"
  maxPoolSize: 10
  dbs:
    test: "test"
    job: "job"
    x: "17x"
  # 默认 认证机制
  authMechanism: "SCRAM-SHA-1"

# https://cloud.mongodb.com/ 创建的 free cluster
mongodbCluster:
  appUrl: "mongodb+srv://<username>:<password>@clusterfree.p7rd5.mongodb.net/<dbname>?retryWrites=true&w=majority"
  username: "17x"
  password: "mongodb12345"
  maxPoolSize: 10
  dbs:
    test: "test"
    job: "job"
    x: "17x"
  # 默认 认证机制
  authMechanism: "SCRAM-SHA-1"


pgsql:
  username: "postgres"
  password: "123456"
  host: "123.57.236.125"
  port: 5432
  database: "sampdb"
  poolSize: 10

mysql:
  username: "root"
  password: "123456"
  host: "123.57.236.125"
  port: 3306
  database:  "sampdb"
  timeout: "10s"
  tableNamePrefix: "x_"

rabbitmq:
  username: "guest"
  password: "guest"
  host: "123.57.236.125"
  port: 5672

etcd:
  endpoints:
    - "http://123.57.236.125:12379"
    - "http://123.57.236.125:22379"
    - "http://123.57.236.125:32379"
  dialTimeout: "5s"
  username: ""
  password: ""
  # TLS相关
  certFile: ""
  keyFile: ""
  trustedCAFile: ""

# ElasticSearch official sdk
elasticsearch-official:
  address:
    - "http://47.93.123.142:9201"
    - "http://47.93.123.142:9201"
    - "http://47.93.123.142:9202"
  username: ""
  password: ""
  # TLS相关
  certFile: ""
  # 响应超时
  timeout: "10s"
# ElasticSearch 第三方 sdk
elasticsearch:
  addr: "http://192.168.1.120:9200"
  username: ""
  password: ""


tbk:
  appKey: ""
  appSecret: ""
  router: "http://gw.api.taobao.com/router/rest"
  session: ""
  timeout: "3s"


