# 全局配置
global:
  # 数据采集间隔
  scrape_interval: 5s
  # 监控检查间隔
  evaluation_interval: 5s

# 报警规则
rule_files:
# - "first.rules"
# - "second.rules"

# 采集任务
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9101
  - job_name: jaeger-agent
    static_configs:
      - targets:
          # 不在同一个网络下则需要通过IP访问 ip addr show docker0
          # 由于是通过容器访问宿主机 localhost 访问的是容器本身
          - localhost:14271
  - job_name: jaeger-collector
    static_configs:
      - targets:
          - localhost:14269
  - job_name: jaeger-query
    static_configs:
      - targets:
          - localhost:16687
